# Generated by Django 4.1.7 on 2023-04-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closer', '0002_alter_closer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='closer',
            name='nombre_wp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
