# Generated by Django 4.1.7 on 2023-04-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closer', '0003_closer_nombre_wp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closer',
            name='nombre_wp',
        ),
    ]
