# Generated by Django 4.1.7 on 2023-04-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='lead',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
