# Generated by Django 4.1.7 on 2023-04-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_whatsapp_alter_lead_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
