# Generated by Django 4.1.7 on 2023-04-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
